Add full screen mode
AmmarAbouZor/tui-journal pull request #281
Opened 2024-01-04 19:32 UTC by orhun

closes #271 

press ctrl+f to toggle full screen for the selected view:

![rec_20240104T222740](https://github.com/AmmarAbouZor/tui-journal/assets/24392180/51078ba5-dcb2-48ac-a0b6-106651500311)

> The command to switch between the active controls should exit full-screen mode if it active before

I personally liked the other way around (keep it full screen) but let me know if you want this behavior changed!

2024-01-04 20:41 UTC, AmmarAbouZor requested changes
This looks great, I've tested it and it works great too. Thanks!

I think your suggestion to keep switching between the controls in full-screen mode works better than mine, but we need to add more infos to the users in the footer with the shortcut to exit the full-screen mode, and maybe to cycle between active control.

I would suggest to add the shortcuts for the full-screen mode command and cycle to next object to the footer in full-screen mode only. The place for them is before show help command. You can try to add the both commands at first and if you feel that the footer  is too cluttered then we'll keep the toggle full-screen mode command and remove the other one.

2024-01-05 13:11 UTC, orhun commented
It felt too crowded when I added "cycle active control" keymap to the footer so I only added "toggle full screen" for now:

![rec_20240105T160838](https://github.com/AmmarAbouZor/tui-journal/assets/24392180/948f85de-5afa-44dc-973c-16d0d50a65b0)

As you requested, it is only shown on full screen mode.

---

While doing this, I noticed a bug:

![rec_20240105T160923](https://github.com/AmmarAbouZor/tui-journal/assets/24392180/1c1ad4f9-f54a-4853-8ab7-adaee92132c0)

TUI is not being redrawn if you resize the terminal or change the font size (unless you press a key afterwards).

I would also like to fix this. Let me know if I should submit another issue for tracking!

2024-01-05 13:41 UTC, AmmarAbouZor approved these changes

2024-01-05 13:49 UTC, AmmarAbouZor commented
This looks great! 
Thanks @orhun :heart: :tada:

2024-01-05 13:50 UTC, merged