feat: support toggling tag filter
AmmarAbouZor/tui-journal pull request #458
Opened 2024-09-09 17:27 UTC by orhun

see the comments in #455

Now you can press `Ctrl-t` to toggle the tag filter.

Let me know if you like this and I think we can add the key binding text to the bottom.

2024-09-11 13:05 UTC, AmmarAbouZor requested changes
Very thanks for the PR :heart:
This works in the most cases but there are some edge cases that we need to consider as well, besides some app design choices that I would prefer since I'm more familiar with the ins and out of the app.

I've mentioned all the points in the comments, and if you prefer, I can take it from here and do the needed changes since they could be too complicated for someone who isn't familiar enough with the code base. 
Please let me know if you want me to continue on your work, or ask me for more info if you have any questions while developing the requested changes :+1:

2024-09-26 09:07 UTC, orhun commented on src/app/ui/commands/mod.rs
> +    ToggleTagFilter,
37719a09912dbee30774db39ce1728fc2a24507b

2024-09-26 09:08 UTC, orhun commented on src/app/ui/commands/mod.rs
> +                "Toggle Tag Filter",
8400c0c3f03a6c072a569054298b1aeaec8777e0

2024-09-26 09:19 UTC, orhun commented on src/app/ui/commands/entries_list_cmd.rs
> +    Ok(HandleInputReturnType::Handled)
I did my best to address these points, but 3rd and 5th wasn't clear to me.

98ed25528dd1957eee0aad418b8ff9ec514448eb

2024-09-26 09:20 UTC, orhun commented
Thanks for the review and sorry for the delay! I addressed the comments to the best of my abilities, feel free to take it from here :)

2024-09-27 12:36 UTC, AmmarAbouZor commented
Thanks for the Fixes, I'll take it from here to fix the issues with exiting filters & Adding unit-tests and The case if the current journal has unsaved changes

2024-09-27 14:23 UTC, orhun commented
Perfect, thank you :)

2024-09-27 18:07 UTC, AmmarAbouZor commented
Closed in favor of #468

2024-09-27 18:07 UTC, closed without merging